### ISSUE TITLE
Confusion about the example code objects

### ISSUE THREAD

**Issue by egkennedy** [James-Thorson/EOFR#3]
I am struggling a bit to understand the example code. If I am reading it right, all the environmental information for the physical submodel is inputted into the Data_Geostat object, structured and labeled as if it were catch data in a VAST model. Is that correct? If so, to add additional environmental information (e.g., salinity), would I just label each new environmental variable with a new species number in the spp column? Also, if you are passing environmental information to make_data, do you need to make some changes to the default ObsModel parameter? There don't seem to be any options for an identity link function in the help documentation that I have found.

Thank you for clarifying.

**Comment by James-Thorson-NOAA** [comment]
I hope to merge with VAST eventually, in which case there would be more options for the response distribution, link function, etc.  However, for now the physics component is assumed to follow a normal distribution with an identity link.

And yes, other environmental information goes in as the equivalent of a new variable c.

**Comment by egkennedy** [comment]
Thank you! I had mistakenly assumed that the make_data function was the same as the VAST version with the same defaults.
